# Generated by Django 4.2.10 on 2024-03-05 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetails',
            name='image',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
