# Generated by Django 4.2.10 on 2024-03-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemdetails',
            old_name='temp',
            new_name='weight',
        ),
        migrations.RemoveField(
            model_name='itemdetails',
            name='fertilization',
        ),
        migrations.RemoveField(
            model_name='itemdetails',
            name='light',
        ),
        migrations.RemoveField(
            model_name='itemdetails',
            name='plantsize',
        ),
        migrations.RemoveField(
            model_name='itemdetails',
            name='water',
        ),
        migrations.AddField(
            model_name='itemdetails',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
