# Generated by Django 4.2.10 on 2024-03-05 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdetails',
            name='color',
        ),
    ]
