# Generated by Django 4.2.10 on 2024-03-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_remove_itemdetails_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdetails',
            name='desc',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='itemdetails',
            name='fertilization',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='itemdetails',
            name='light',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='itemdetails',
            name='plantsize',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='itemdetails',
            name='temp',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='itemdetails',
            name='water',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
