# Generated by Django 4.2.10 on 2024-03-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='net',
            field=models.FloatField(null=True),
        ),
    ]
